url: https://cukes.info
name: Cucumber
description: Cucumber. Simple, Human Collaboration
author: Cucumber Limited
copyright: Cucumber Limited
edit_url: https://github.com/cucumber/website/edit/master/apps/dynamic/views
