url: https://cucumber-website.herokuapp.com
name: Cucumber
description: Cucumber. Simple, Human Collaboration
author: Cucumber Limited
copyright: Cucumber Limited
markdown: redcarpet
pygments: true
encoding: UTF-8
exclude:
  - assets
  - node_modules
  - bower_components
  - bower.json
  - package.json
  - Makefile
  - README.md

# Custom vars
email_signup: https://customers.cucumber.pro/emails
stripe_publishable_key: pk_live_CM7KruXBBpWbcX4YezpjncEm
stripe_charge_url: https://customers.cucumber.pro/subscriptions

# Blog
authors:
  aslak:
    display_name: Aslak Hellesøy
    email: aslak@cucumber.pro
    gravatar: 0be0e4aa42aacd9a8a95c792de273ca7
  matt:
    display_name: Matt Wynne
    email: matt@cucumber.pro
    gravatar: cdf378de2284d8acf137122e541caa28
  julien:
    display_name: Julien Biezemans
    email: julien@cucumber.pro
    gravatar: 07193608fb3c70b2a9449d6cafd6d31a
